name: inhabit_realties
description: "We present your dreams"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  fl_chart: ^0.64.0
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  http_parser: ^4.0.2
  connectivity_plus: ^6.1.4
  awesome_snackbar_content: ^0.1.3
  image_picker: ^1.0.4
  file_picker: ^8.0.0+1
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
  country_state_city: ^0.1.6
  lottie: ^2.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  share_plus: ^7.2.1
  provider: ^6.1.2
  flutter_map: ^6.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  latlong2: ^0.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/applogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/animations/
